name: CICD to Firebase Hosting

# on: [push]
on:
  push:
    branches:
      - "do-not-trigger"  # 存在しないブランチ

jobs:
    FrontDeploy:
        name: FrontDeploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: 21.x
                  registry-url: "https://registry.npmjs.org"
            - name: Build
              run: |
                  npm install
                  npm run build
                  npm install -g firebase-tools
            - name: Test
              run: |
                  npm run test
            - name: Deploy to Firebase Hosting
              run: |
                  firebase deploy --token $FIREBASE_TOKEN
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
                  VITE_APP_SUPABASE_URL: ${{ secrets.VITE_APP_SUPABASE_URL }}
                  VITE_APP_SUPABASE_ANON_KEY: ${{ secrets.VITE_APP_SUPABASE_ANON_KEY }}